spring:
  application:
    name: spring-boot-survey-controller

  cloud:
    azure:
      active-directory:
        b2c:
          enabled: true
          base-uri: 'https://reubenorg.b2clogin.com/reubenorg.onmicrosoft.com'
          credential:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
          login-flow: sign-up-or-sign-in
          logout-success-url: 'http://localhost:8080/login'
          user-flows:
            sign-up-or-sign-in: "B2C_1_authtentication-flow"
#            profile-edit: <your-profile-edit-user-flow-name>
#            password-reset: <your-password-reset-user-flow-name>
#          user-name-attribute-name: <your-user-name-attribute-name>























