package com.reuben.cms.model;


import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;

import lombok.Data;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedUuid;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.*;

import java.util.UUID;

@DynamoDbBean
@Data
@ToString(callSuper = true)
public class Article {

    @Setter
    private String id; // Unique identifier for each article, should be string for DynamoDB.

    @Setter
    private String title;

    @Setter
    @Getter
    private String content;

    @Setter
    @Getter
    private List<String> categories;

//    private ArrayList<String> tags;

    @Getter
    @Setter
    private String status; // Expected to be either "draft" or "published".

    private String publishDate = LocalDateTime.now().toString(); // Optional, used when an article is published.

    @DynamoDbPartitionKey
    public String getId() {
        return id;
    }

    @DynamoDbSortKey
    public String getTitle() {
        return title;
    }


    //    public ArrayList<String> getTags() {
//        return tags;
//    }
//    public void setTags(ArrayList<String> tags) {
//        this.tags = tags;
//    }


    @DynamoDbSortKey
    public String getPublishDate() {
        return publishDate.toString();
    }
    public void setPublishDate(String publishDate) {
        this.publishDate = publishDate;
    }

}


